const PRODUCTS = [
  {
    id: 1,
    name: "Body Splash 200ml O Boticário",
    category: "Beleza",
    store: "Shopee",
    description: "Fragrância corporal leve para usar no dia a dia.",
    oldPrice: null,
    price: null,
    image: "images/produto-01-body-splash.jpg",
    link: "https://s.shopee.com.br/20uEP3Q1UA",
    badge: "Mais vendido",
    featured: 100
  },
  {
    id: 2,
    name: "Kit Nivea Óleo de Banho + Esfoliante",
    category: "Beleza",
    store: "Shopee",
    description: "Kit para limpeza, hidratação e cuidados com a pele durante o banho.",
    oldPrice: null,
    price: null,
    image: "images/produto-02-kit-nivea.jpg",
    link: "https://s.shopee.com.br/5LAgNFgW22",
    badge: "Oferta",
    featured: 99
  },
  {
    id: 3,
    name: "Kit Boca Rosa com 4 Produtos",
    category: "Beleza",
    store: "Shopee",
    description: "Kit com base líquida, pó, máscara de cílios e corretivo.",
    oldPrice: 100.00,
    price: 51.78,
    image: "images/produto-03-kit-boca-rosa.jpg",
    link: "https://s.shopee.com.br/7fYb9Yg1oX",
    badge: "Escolha da Bella",
    featured: 98
  },
  {
    id: 4,
    name: "Sérum Facial SKIN1004 Madagascar",
    category: "Beleza",
    store: "Shopee",
    description: "Ampola facial para ajudar na luminosidade e uniformização da pele.",
    oldPrice: 127.95,
    price: 43.98,
    image: "images/produto-04-serum-skin1004.jpg",
    link: "https://s.shopee.com.br/3Vj2Bv8tMm",
    badge: "Novidade",
    featured: 97
  },
  {
    id: 5,
    name: "Kit L'Oréal Elseve Óleo Extraordinário",
    category: "Beleza",
    store: "Shopee",
    description: "Linha de cuidados capilares para nutrição, brilho e maciez.",
    oldPrice: 47.90,
    price: 44.90,
    image: "images/produto-05-kit-elseve.jpg",
    link: "https://s.shopee.com.br/Lm0Q7l0gl",
    badge: "Oferta",
    featured: 96
  },
  {
    id: 6,
    name: "Kit Principia Skincare Pele Sensível + Protetor Solar FPS 60",
    category: "Beleza",
    store: "Mercado Livre",
    description: "Kit completo para rotina de cuidados com a pele sensível, incluindo protetor solar FPS 60.",
    oldPrice: null,
    price: null,
    image: "images/produto-06-kit-principia.jpg",
    link: "https://meli.la/2jMMLJe",
    badge: "Escolha da Bella",
    featured: 95
  },
  {
    id: 7,
    name: "Creatina Monohidratada Pura Dark Lab 1kg",
    category: "Fitness",
    store: "Mercado Livre",
    description: "Creatina monohidratada pura, sem sabor, para auxiliar no desempenho e recuperação muscular.",
    oldPrice: null,
    price: null,
    image: "images/produto-07-creatina-dark-lab.jpg",
    link: "https://meli.la/1ZdaUuv",
    badge: "Mais vendido",
    featured: 94
  },
  {
    id: 8,
    name: "Jogo de Toalhas Karsten 100% Algodão 4 Peças",
    category: "Casa",
    store: "Mercado Livre",
    description: "Jogo de toalhas macias e absorventes em 100% algodão.",
    oldPrice: null,
    price: null,
    image: "images/produto-08-toalhas-karsten.jpg",
    link: "https://meli.la/18BxaKc",
    badge: "Novidade",
    featured: 93
  },
  {
    id: 9,
    name: "Kit 3 Organizadores para Geladeira com Tampa",
    category: "Organização",
    store: "Mercado Livre",
    description: "Organizadores para armazenar frutas, legumes e outros alimentos na geladeira.",
    oldPrice: null,
    price: null,
    image: "images/produto-09-organizadores-geladeira.jpg",
    link: "https://meli.la/22SN2bo",
    badge: "Oferta",
    featured: 92
  },
  {
    id: 10,
    name: "Jogo de Lençol Queen 400 Fios 3 Peças",
    category: "Casa",
    store: "Mercado Livre",
    description: "Jogo de lençol Queen com elástico, toque macio e acabamento rose poá.",
    oldPrice: null,
    price: null,
    image: "images/produto-10-lencol-queen.jpg",
    link: "https://meli.la/2eEXmSg",
    badge: "Mais vendido",
    featured: 91
  }
];
