const PRODUCTS = [
  {
    id: 1,
    name: "Body Splash 200ml O Boticário",
    category: "Beleza",
    store: "Shopee",
    description: "Fragrância corporal leve para usar no dia a dia.",
    oldPrice: null,
    price: null,
    image: "images/produto-01-body-splash.jpg",
    link: "https://s.shopee.com.br/20uEP3Q1UA",
    badge: "Mais vendido",
    featured: 100
  },
  {
    id: 2,
    name: "Kit Nivea Óleo de Banho + Esfoliante",
    category: "Beleza",
    store: "Shopee",
    description: "Kit para limpeza, hidratação e cuidados com a pele durante o banho.",
    oldPrice: null,
    price: null,
    image: "images/produto-02-kit-nivea.jpg",
    link: "https://s.shopee.com.br/5LAgNFgW22",
    badge: "Oferta",
    featured: 99
  },
  {
    id: 3,
    name: "Kit Boca Rosa com 4 Produtos",
    category: "Beleza",
    store: "Shopee",
    description: "Kit com base líquida, pó, máscara de cílios e corretivo.",
    oldPrice: 100.00,
    price: 51.78,
    image: "images/produto-03-kit-boca-rosa.jpg",
    link: "https://s.shopee.com.br/7fYb9Yg1oX",
    badge: "Escolha da Bella",
    featured: 98
  },
  {
    id: 4,
    name: "Sérum Facial SKIN1004 Madagascar",
    category: "Beleza",
    store: "Shopee",
    description: "Ampola facial para ajudar na luminosidade e uniformização da pele.",
    oldPrice: 127.95,
    price: 43.98,
    image: "images/produto-04-serum-skin1004.jpg",
    link: "https://s.shopee.com.br/3Vj2Bv8tMm",
    badge: "Novidade",
    featured: 97
  },
  {
    id: 5,
    name: "Kit L'Oréal Elseve Óleo Extraordinário",
    category: "Beleza",
    store: "Shopee",
    description: "Linha de cuidados capilares para nutrição, brilho e maciez.",
    oldPrice: 47.90,
    price: 44.90,
    image: "images/produto-05-kit-elseve.jpg",
    link: "https://s.shopee.com.br/Lm0Q7l0gl",
    badge: "Oferta",
    featured: 96
  },
  {
    id: 6,
    name: "Kit Principia Skincare Pele Sensível + Protetor Solar FPS 60",
    category: "Beleza",
    store: "Mercado Livre",
    description: "Kit completo para rotina de cuidados com a pele sensível, incluindo protetor solar FPS 60.",
    oldPrice: null,
    price: null,
    image: "images/produto-06-kit-principia.jpg",
    link: "https://meli.la/2jMMLJe",
    badge: "Escolha da Bella",
    featured: 95
  },
  {
    id: 7,
    name: "Creatina Monohidratada Pura Dark Lab 1kg",
    category: "Fitness",
    store: "Mercado Livre",
    description: "Creatina monohidratada pura, sem sabor, para auxiliar no desempenho e recuperação muscular.",
    oldPrice: null,
    price: null,
    image: "images/produto-07-creatina-dark-lab.jpg",
    link: "https://meli.la/1ZdaUuv",
    badge: "Mais vendido",
    featured: 94
  },
  {
    id: 8,
    name: "Jogo de Toalhas Karsten 100% Algodão 4 Peças",
    category: "Casa",
    store: "Mercado Livre",
    description: "Jogo de toalhas macias e absorventes em 100% algodão.",
    oldPrice: null,
    price: null,
    image: "images/produto-08-toalhas-karsten.jpg",
    link: "https://meli.la/18BxaKc",
    badge: "Novidade",
    featured: 93
  },
  {
    id: 9,
    name: "Kit 3 Organizadores para Geladeira com Tampa",
    category: "Organização",
    store: "Mercado Livre",
    description: "Organizadores para armazenar frutas, legumes e outros alimentos na geladeira.",
    oldPrice: null,
    price: null,
    image: "images/produto-09-organizadores-geladeira.jpg",
    link: "https://meli.la/22SN2bo",
    badge: "Oferta",
    featured: 92
  },
  {
    id: 10,
    name: "Jogo de Lençol Queen 400 Fios 3 Peças",
    category: "Casa",
    store: "Mercado Livre",
    description: "Jogo de lençol Queen com elástico, toque macio e acabamento rose poá.",
    oldPrice: null,
    price: null,
    image: "images/produto-10-lencol-queen.jpg",
    link: "https://meli.la/2eEXmSg",
    badge: "Mais vendido",
    featured: 91
  },
  {
    id: 11,
    name: "Pipoqueira de Silicone 2,5L para Micro-ondas",
    category: "Cozinha",
    store: "Mercado Livre",
    description: "Pipoqueira reutilizável para preparar pipoca no micro-ondas com praticidade.",
    oldPrice: null,
    price: 30.79,
    image: "images/produto-11-pipoqueira.jpg",
    link: "https://meli.la/15gNvFR",
    badge: "Escolha da Bella",
    featured: 90
  },
  {
    id: 12,
    name: "Espelho Orgânico Corpo Inteiro 90x40cm",
    category: "Casa",
    store: "Mercado Livre",
    description: "Espelho decorativo moderno para quarto, closet, sala ou hall de entrada.",
    oldPrice: 129.90,
    price: 78.99,
    image: "images/produto-12-espelho.jpg",
    link: "https://meli.la/177urJw",
    badge: "Oferta",
    featured: 89
  },
  {
    id: 13,
    name: "Jogo de Facas Tramontina Plenus 7 Peças",
    category: "Cozinha",
    store: "Mercado Livre",
    description: "Conjunto de facas Tramontina em aço inox para diferentes preparos.",
    oldPrice: 58.20,
    price: 43.20,
    image: "images/produto-13-facas.jpg",
    link: "https://meli.la/1nssE2E",
    badge: "Mais vendido",
    featured: 88
  },
  {
    id: 14,
    name: "Kit com 8 Rodinhas de Silicone para Móveis",
    category: "Organização",
    store: "Mercado Livre",
    description: "Rodízios reforçados com trava, placa e freio para móveis e bancadas.",
    oldPrice: 29.99,
    price: 28.49,
    image: "images/produto-14-rodinhas.jpg",
    link: "https://meli.la/2y6SbPp",
    badge: "Novidade",
    featured: 87
  },
  {
    id: 15,
    name: "Sofá Beny Living 2 Lugares com Almofadas",
    category: "Casa",
    store: "Mercado Livre",
    description: "Sofá moderno de dois lugares para sala, recepção, clínica ou escritório.",
    oldPrice: 850.00,
    price: 765.00,
    image: "images/produto-15-sofa.jpg",
    link: "https://meli.la/2UPN6CJ",
    badge: "Escolha da Bella",
    featured: 86
  },
  {
    id: 16,
    name: "Triturador Manual de Alimentos",
    category: "Cozinha",
    store: "Mercado Livre",
    description: "Triturador manual para desfiar carne, frango e preparar diferentes alimentos.",
    oldPrice: null,
    price: 24.50,
    image: "images/produto-16-triturador.jpg",
    link: "https://meli.la/1Aaz5De",
    badge: "Oferta",
    featured: 85
  },
  {
  id: 17,
  name: "Barra de Proteína Whey Grego Havanna Display 12 Unidades",
  category: "Fitness",
  store: "Mercado Livre",
  description: "Display com 12 barras de proteína sabor brownie e doce de leite Havanna.",
  oldPrice: 104.00,
  price: 67.89,
  image: "images/produto-17-barra-whey-grego.jpg",
  link: "https://meli.la/1o2ktth",
  badge: "Oferta",
  featured: 84
},
  {
  id: 18,
  name: "Leave-in Elseve Collagen Lifter 100ml",
  category: "Beleza",
  store: "Mercado Livre",
  description: "Leave-in para cabelos finos com efeito volume e fortalecimento.",
  oldPrice: null,
  price: 32.19,
  image: "images/produto-18-elseve-collagen.jpg",
  link: "https://meli.la/1V28XhV",
  badge: "Novidade",
  featured: 83
},
  {
  id: 19,
  name: "Top Fitness Feminino com Bojo",
  category: "Moda",
  store: "Mercado Livre",
  description: "Top esportivo confortável para academia, caminhada e treino.",
  oldPrice: 47.97,
  price: 30.49,
  image: "images/produto-19-top-fitness.jpg",
  link: "https://meli.la/1EJBm3R",
  badge: "Mais vendido",
  featured: 82
},
  {
  id: 20,
  name: "Loção Hidratante CeraVe 473ml",
  category: "Beleza",
  store: "Mercado Livre",
  description: "Hidratante corporal com ceramidas e ácido hialurônico.",
  oldPrice: 141.90,
  price: 89.90,
  image: "images/produto-20-cerave.jpg",
  link: "https://meli.la/2WdSw8y",
  badge: "Escolha da Bella",
  featured: 81
},
  {
  id: 21,
  name: "Amaciante Downy Concentrado Brisa de Verão 3L",
  category: "Casa",
  store: "Mercado Livre",
  description: "Amaciante concentrado com perfume duradouro e alto rendimento.",
  oldPrice: 66.90,
  price: 45.99,
  image: "images/produto-21-downy.jpg",
  link: "https://meli.la/22cRoou",
  badge: "Oferta",
  featured: 80
},
  {
  id: 22,
  name: "Assento Sanitário Universal Astra Slim",
  category: "Casa",
  store: "Mercado Livre",
  description: "Assento sanitário resistente com design moderno e confortável.",
  oldPrice: 89.90,
  price: 58.10,
  image: "images/produto-22-astra.jpg",
  link: "https://meli.la/2wdzSX1",
  badge: "Mais vendido",
  featured: 79
},
  {
  id: 23,
  name: "Aparelho de Jantar Tramontina Azzura 20 Peças",
  category: "Casa",
  store: "Mercado Livre",
  description: "Conjunto em porcelana para deixar sua mesa ainda mais elegante.",
  oldPrice: null,
  price: 534.45,
  image: "images/produto-23-tramontina-azzura.jpg",
  link: "https://meli.la/2VctFXc",
  badge: "Escolha da Bella",
  featured: 78
},
  {
  id: 24,
  name: "Kit Boleira Decorativa com 5 Peças",
  category: "Casa",
  store: "Mercado Livre",
  description: "Kit para decoração de festas, doces e bolos.",
  oldPrice: 99.99,
  price: 78.11,
  image: "images/produto-24-kit-boleira.jpg",
  link: "https://meli.la/1NtydUy",
  badge: "Novidade",
  featured: 77
},
  {
  id: 25,
  name: "Jogo de Jantar Oxford Unni Brisa 20 Peças",
  category: "Casa",
  store: "Mercado Livre",
  description: "Jogo de jantar em porcelana para uso diário e ocasiões especiais.",
  oldPrice: 499.90,
  price: 256.40,
  image: "images/produto-25-oxford-unni.jpg",
  link: "https://meli.la/1xQBmpX",
  badge: "Escolha da Bella",
  featured: 76
},
  {
  id: 26,
  name: "Interruptor Inteligente Wi-Fi Alexa",
  category: "Tecnologia",
  store: "Mercado Livre",
  description: "Interruptor inteligente compatível com Alexa e Google Assistente.",
  oldPrice: 49.80,
  price: 34.90,
  image: "images/produto-26-interruptor-inteligente.jpg",
  link: "https://meli.la/2cRujon",
  badge: "Novidade",
  featured: 75
},
 {
  id: 27,
  name: "Ômegafor Plus Ômega 3 120 Cápsulas",
  category: "Fitness",
  store: "Mercado Livre",
  description: "Suplemento de Ômega 3 de alta concentração.",
  oldPrice: 240.00,
  price: 118.50,
  image: "images/produto-27-omegafor.jpg",
  link: "https://meli.la/1ZLQbeY",
  badge: "Mais vendido",
  featured: 74
}

